version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    #    local:container
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb-data:
    driver: local