apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.10
        ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "1000m"
        limits:
          memory: "128Mi"
          cpu: "1500m"
