version: "3"

services:

  mongo:
    container_name: mongo
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
      MONGO_INITDB_DATABASE: "local"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - coder

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: "123456"
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
  
  networks:
  coder: